Describe how to start api before contributing to the web-app
Sage-Bionetworks/challenge-registry pull request #201
Opened 2022-05-23 02:23 UTC by tschaffter

Fixes #166

2022-05-25 13:37 UTC, rrchai requested changes

2022-05-25 13:37 UTC, rrchai commented on apps/web-app/README.md
> +    docker compose up api-db -d
After getting updates from upstream, I have to use `docker compose up challenge-registry-api -d` to start api now.

2022-05-25 23:12 UTC, tschaffter commented
@rrchai GH does not let me ask you to re-review this PR: nothing happens when I click on the `Re-request review` button. Can you please let me know in the chat whether this PR now looks good?

2022-05-25 23:24 UTC, rrchai commented
@tschaffter LGTM!

2022-05-25 23:24 UTC, rrchai approved these changes

2022-05-26 19:24 UTC, vpchung approved these changes

2022-05-26 20:43 UTC, merged