Update home page
Sage-Bionetworks/challenge-registry pull request #358
Opened 2022-06-23 07:01 UTC by vpchung

This PR will update the HTML and SCSS of the home page components:

- [ ] challenge-search
- [ ] statistics-viewer
- [ ] topics-viewer
- [ ] challenge-host-list
- [ ] challenge-registration
- [ ] featured-challenge-list
- [ ] sponsor-list

2022-06-30 20:21 UTC, vpchung commented
`topics-viewer` component update finished:

**Before**
![Screen Shot 2022-06-30 at 1 02 44 PM](https://user-images.githubusercontent.com/9377970/176771451-612547be-aebe-429c-bbe1-0816fd047cc8.png)

**After**
![Screen Shot 2022-06-30 at 1 20 28 PM](https://user-images.githubusercontent.com/9377970/176771490-2dcf52af-5fbf-404d-ac38-50cf271e52eb.png)

2022-06-30 20:29 UTC, vpchung commented
`challenge-host-list` component update finished:

**Before**
![Screen Shot 2022-06-30 at 1 02 49 PM](https://user-images.githubusercontent.com/9377970/176772629-154d56bf-5f1a-4775-aa39-620924883a6f.png)

**After**
![Screen Shot 2022-06-30 at 1 28 08 PM](https://user-images.githubusercontent.com/9377970/176772663-43182aad-4dbb-48f5-8d01-d32a9530dc41.png)

2022-06-30 21:20 UTC, vpchung commented
`challenge-registration` component update finished:

**Before**
![Screen Shot 2022-06-30 at 1 02 55 PM](https://user-images.githubusercontent.com/9377970/176780228-739e9d94-3c13-492d-9ee6-52faea954bf0.png)

**After**
![Screen Shot 2022-06-30 at 2 20 04 PM](https://user-images.githubusercontent.com/9377970/176780243-7d053ff9-d6c5-4359-b646-4fcf3f69ca37.png)

2022-06-30 21:54 UTC, vpchung commented
`challenge-registration` component update finished:

**Before**
![Screen Shot 2022-06-30 at 1 02 55 PM](https://user-images.githubusercontent.com/9377970/176785365-87122363-11d3-446b-9b91-4c65601cb148.png)

**After**
![Screen Shot 2022-06-30 at 2 54 00 PM](https://user-images.githubusercontent.com/9377970/176785387-47b16d3d-625a-495b-b691-d4475238395b.png)

2022-06-30 23:00 UTC, vpchung commented
`featured-challenge-list` component update finished:

**Before**
![Screen Shot 2022-06-30 at 1 03 02 PM](https://user-images.githubusercontent.com/9377970/176792241-2c36e2ac-301e-4073-a58a-2f09eae6efd3.png)

**After**
![Screen Shot 2022-06-30 at 3 59 28 PM](https://user-images.githubusercontent.com/9377970/176792256-6df6a82c-e99c-4702-80de-5862096a214f.png)

2022-06-30 23:26 UTC, vpchung commented
`sponsor-list` component update finished:

**Before**
![Screen Shot 2022-06-30 at 1 03 08 PM](https://user-images.githubusercontent.com/9377970/176794644-b6367cfa-f682-4841-a816-5b103a1c740a.png)

**After**
![Screen Shot 2022-06-30 at 4 25 10 PM](https://user-images.githubusercontent.com/9377970/176794652-e17f7fb8-48ae-433b-8c9b-1555b897aeea.png)

2022-06-30 23:27 UTC, vpchung commented
@tschaffter @rrchai I finished updating the home page so that the typography is displayed among the different components.  There are some colors that remain in the SCSS, but I will tackle that in my next PR (where I will restructure where all of the themes/styles go).

2022-07-01 01:31 UTC, tschaffter requested changes

2022-07-01 01:31 UTC, tschaffter commented on libs/challenge-registry/home/src/lib/challenge-host-list/challenge-host-list.component.html
> +          src="https://raw.githubusercontent.com/Sage-Bionetworks/rocc-app/7e8c4f27849796ce52df74118de32b3a6f1159e1/images/logo/sage-bionetworks.png"
We should add this image to the challenge-registry-assets project.

2022-07-01 01:31 UTC, tschaffter commented on libs/challenge-registry/home/src/lib/challenge-host-list/challenge-host-list.component.html
> +          src="https://raw.githubusercontent.com/Sage-Bionetworks/rocc-app/7e8c4f27849796ce52df74118de32b3a6f1159e1/images/logo/miccai.png"
We should add this image to the challenge-registry-assets project.

2022-07-01 01:31 UTC, tschaffter commented on libs/challenge-registry/home/src/lib/challenge-host-list/challenge-host-list.component.html
> +          src="https://raw.githubusercontent.com/Sage-Bionetworks/rocc-app/7e8c4f27849796ce52df74118de32b3a6f1159e1/images/logo/cagi.png"
We should add this image to the challenge-registry-assets project.

2022-07-01 01:31 UTC, tschaffter commented on libs/challenge-registry/home/src/lib/challenge-host-list/challenge-host-list.component.html
> +        <img src="https://raw.githubusercontent.com/Sage-Bionetworks/rocc-app/main/images/logo/precisionfda.png"
We should add this image to the challenge-registry-assets project.

2022-07-01 01:32 UTC, tschaffter commented
> Note: I'm not sure how to implement @media into Angular Material Theme yet... for now, the @media typography will remain in home.scss.

Sounds good! Let's track this in a ticket that we can revisit in the future.

2022-07-01 13:08 UTC, rrchai approved these changes

2022-07-01 13:23 UTC, merged